### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by cfrietschy** [leitwerk-de/lssh#2]
https://github.com/leitwerk-ag/lssh/blob/b47a2bd1b101732939bb5ac9d528cb0332756c4f/lssh/tui_dialog.py#L9

lssh throws the following error if is it started inside tmux

```
Traceback (most recent call last):
  File "/usr/local/bin/lssh", line 14, in <module>
    main.main(hosts_dir, update_hosts)
  File "/usr/local/lib/lssh/main.py", line 20, in main
    cli.main(hosts_dir, update_hosts, attributes)
  File "/usr/local/lib/lssh/cli.py", line 113, in main
    connect(args, user, substring, additional_substrings, hosts_dir)
  File "/usr/local/lib/lssh/cli.py", line 169, in connect
    selected, proxy_chain = select_host(substring, additional_substrings, hosts_dir)
  File "/usr/local/lib/lssh/cli.py", line 159, in select_host
    choice = tui_dialog.hierarchical_option_dialog(options, displaynames, 'select customer', 'select host')
  File "/usr/local/lib/lssh/tui_dialog.py", line 58, in hierarchical_option_dialog
    term_variable_workaround()
  File "/usr/local/lib/lssh/tui_dialog.py", line 9, in term_variable_workaround
    os.environ.putenv("TERM", "xterm-256color")
AttributeError: '_Environ' object has no attribute 'putenv'
```

**Comment by cfrietschy** [comment]
`os.putenv("TERM", "xterm-256color")` fixes the error
